#!/usr/bin/env node
// Agent Toolbox generator.
// Canon is the source of truth: `Agent Toolbox.md` holds the roster of agent
// profiles (a fenced ```yaml block). This projects each profile into a
// `.claude/agents/<name>.md` definition the Claude Code harness reads at
// session start. Nobody hand-edits `.claude/agents/`; edit the canon list and
// re-run this. Mirrors the `_`-symlink @import projection and the Commons
// reading the Shop toolbox.
//
// Usage:  node _ops/agent-toolbox/generate.mjs [--check]
//   --check : parse + report, write nothing (dry run).

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..", "..");            // palace root
const CANON = resolve(ROOT, "Agent Toolbox.md");
const OUT_DIR = resolve(ROOT, ".claude", "agents");

const CHARTER = `You are a palace worker. Read before you write. Cite the file (path:line) for every claim about the palace. Hand back drafts and findings rather than acting unbidden — your bias is to offer, not change. Write and speak plainly, in the palace voice, no hype. Do exactly the job you were addressed with and nothing more.`;

// --- minimal parser for the roster's fenced yaml block -----------------------
// Structure (2-space indent per level):
//   profiles:
//     <name>:
//       for: "<text>"
//       tools: [A, B, C]
function parseRoster(md) {
  const m = md.match(/```yaml\s*\n([\s\S]*?)\n```/);
  if (!m) throw new Error("no ```yaml roster block found in Agent Toolbox.md");
  const lines = m[1].split("\n");
  const profiles = {};
  let cur = null;
  for (const raw of lines) {
    if (!raw.trim() || raw.trim().startsWith("#")) continue;
    if (/^profiles:\s*$/.test(raw)) continue;
    let mm;
    if ((mm = raw.match(/^ {2}([a-z0-9-]+):\s*$/))) {          // profile name
      cur = mm[1];
      profiles[cur] = { for: "", tools: [] };
    } else if ((mm = raw.match(/^ {4}for:\s*"(.*)"\s*$/))) {   // description
      if (cur) profiles[cur].for = mm[1];
    } else if ((mm = raw.match(/^ {4}tools:\s*\[(.*)\]\s*$/))) { // tool list
      if (cur) profiles[cur].tools = mm[1].split(",").map((t) => t.trim()).filter(Boolean);
    } else {
      throw new Error(`unparsed roster line: ${JSON.stringify(raw)}`);
    }
  }
  if (!Object.keys(profiles).length) throw new Error("roster block parsed to zero profiles");
  return profiles;
}

function renderAgent(name, prof) {
  return `---
name: ${name}
description: ${prof.for}
tools: ${prof.tools.join(", ")}
---
<!-- GENERATED by _ops/agent-toolbox/generate.mjs from [[Agent Toolbox]] — do not hand-edit; edit the canon roster and re-run. -->

${CHARTER}
`;
}

// --- run ---------------------------------------------------------------------
const check = process.argv.includes("--check");
const md = readFileSync(CANON, "utf8");
const profiles = parseRoster(md);

if (!check && !existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });

const results = [];
for (const [name, prof] of Object.entries(profiles)) {
  const path = resolve(OUT_DIR, `${name}.md`);
  if (!check) writeFileSync(path, renderAgent(name, prof));
  results.push({ name, tools: prof.tools.length, path: path.replace(ROOT + "/", "") });
}

console.log(`${check ? "[check] " : ""}Agent Toolbox → ${results.length} profile(s):`);
for (const r of results) console.log(`  ${r.name.padEnd(22)} ${r.tools} tools  →  ${r.path}`);
if (check) console.log("(dry run — no files written)");
