// build-roster.mjs — regenerate the Shop Roster as a derived read-model.
//
// The single source of truth for Shop membership is each Specialist's
// `member-of [[The Shop]]` frontmatter link (added in the 2026-06-16 compliance
// migration). This script enumerates every `Shop/*.md` of type specialist/maker,
// reads its frontmatter, and writes a roster table between the
//   <!-- ROSTER:START ... --> / <!-- ROSTER:END -->
// markers in `The Shop.md`. Re-run it whenever a Specialist's status/medium/tool
// changes — the hand-maintained roster that drifted (Maker's prose list was 3+
// Specialists stale) is gone; this can never drift because it is computed.
//
// Run:  node Shop/Maker/build-roster.mjs            (rewrite the block)
//       node Shop/Maker/build-roster.mjs --check    (exit 1 if the block is stale)
// Zero dependencies; a minimal frontmatter scalar reader (no YAML lib), matching
// the rest of the Shop toolchain.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));      // …/Shop/Maker
const SHOP = path.dirname(HERE);                                // …/Shop
const PALACE = path.dirname(SHOP);                              // …/The Palace
const HUB = path.join(PALACE, 'The Shop.md');
const START = '<!-- ROSTER:START — generated by Shop/Maker/build-roster.mjs; do not edit by hand -->';
const END = '<!-- ROSTER:END -->';

// --- minimal frontmatter reader ------------------------------------------------
function frontmatter(text) {
  if (!text.startsWith('---')) return null;
  const end = text.indexOf('\n---', 3);
  if (end < 0) return null;
  return text.slice(3, end);
}
function scalar(fm, key) {
  // matches a top-level `key: value` line (value may be quoted); ignores list items
  const m = fm.match(new RegExp(`^${key}:[ \\t]*(.+?)[ \\t]*$`, 'm'));
  if (!m) return null;
  return m[1].replace(/^["']|["']$/g, '').trim();
}
function declaresShopMembership(fm) {
  // a member-of link whose target is [[The Shop]] — tolerant of flow or block form
  return /member-of/.test(fm) && /\[\[The Shop\]\]/.test(fm);
}

// --- scan ---------------------------------------------------------------------
const files = fs.readdirSync(SHOP).filter((f) => f.endsWith('.md'));
const specialists = [];
const makers = [];
const warnings = [];

for (const f of files) {
  const text = fs.readFileSync(path.join(SHOP, f), 'utf8');
  const fm = frontmatter(text);
  if (!fm) continue;
  const type = scalar(fm, 'type');
  if (type !== 'specialist' && type !== 'maker') continue;
  const rec = {
    title: scalar(fm, 'title') || f.replace(/\.md$/, ''),
    status: scalar(fm, 'status') || '?',
    medium: scalar(fm, 'medium') || '—',
    tool: scalar(fm, 'tool') || '—',
    member: declaresShopMembership(fm),
  };
  if (!rec.member) warnings.push(`${f}: type ${type} but no \`member-of [[The Shop]]\` link`);
  (type === 'specialist' ? specialists : makers).push(rec);
}

// --- order: alive → stub → deprecated, then alphabetical ----------------------
const STATUS_RANK = { alive: 0, stub: 1, deprecated: 2 };
specialists.sort((a, b) =>
  (STATUS_RANK[a.status] ?? 9) - (STATUS_RANK[b.status] ?? 9) || a.title.localeCompare(b.title));

const tally = specialists.reduce((acc, s) => ((acc[s.status] = (acc[s.status] || 0) + 1), acc), {});
const tallyStr = ['alive', 'stub', 'deprecated']
  .filter((k) => tally[k])
  .map((k) => `${tally[k]} ${k}`)
  .join(' · ');

// --- render -------------------------------------------------------------------
// Tool rendered as plain text (not a backtick code-span): backticked `*.js`
// tool names read as broken file paths to the doc-drift linter's path detector.
const rows = specialists.map(
  (s) => `| [[Shop/${s.title}\\|${s.title}]] | ${s.status} | ${s.medium} | ${s.tool} |`);
const makerList = makers
  .sort((a, b) => a.title.localeCompare(b.title))
  .map((m) => `[[${m.title}]] (${m.status})`)
  .join(' · ');

const block = [
  START,
  `*Generated read-model — the roster is each Specialist's \`member-of [[The Shop]]\` declaration, computed by \`Shop/Maker/build-roster.mjs\`. Do not hand-edit; re-run the script. (This replaced a hand-maintained list that had drifted 3+ Specialists stale.)*`,
  '',
  `**${specialists.length} Specialists** — ${tallyStr}. **Makers:** ${makerList}.`,
  '',
  '| Specialist | Status | Medium | Tool |',
  '|---|---|---|---|',
  ...rows,
  END,
].join('\n');

// --- write / check ------------------------------------------------------------
const hub = fs.readFileSync(HUB, 'utf8');
const si = hub.indexOf(START);
const ei = hub.indexOf(END);
let next;
if (si >= 0 && ei > si) {
  next = hub.slice(0, si) + block + hub.slice(ei + END.length);
} else {
  // first run: insert before "## Cross-Pillar Connections", else append
  const anchor = '\n## Cross-Pillar Connections';
  const ai = hub.indexOf(anchor);
  const section = `\n## Roster\n\n${block}\n`;
  next = ai >= 0 ? hub.slice(0, ai) + section + hub.slice(ai) : hub.trimEnd() + '\n' + section;
}

const isCheck = process.argv.includes('--check');
if (isCheck) {
  const stale = next !== hub;
  console.log(stale ? 'STALE — run build-roster.mjs to refresh' : 'roster up to date');
  warnings.forEach((w) => console.warn('  warn:', w));
  process.exit(stale ? 1 : 0);
}

fs.writeFileSync(HUB, next);
console.log(`Wrote roster: ${specialists.length} Specialists (${tallyStr}); ${makers.length} Makers.`);
if (warnings.length) {
  console.warn('Membership warnings:');
  warnings.forEach((w) => console.warn('  -', w));
} else {
  console.log('All Specialists/Makers declare member-of [[The Shop]]. ✓');
}
